name: Release

on:
  push:
    branches:
      - main # This makes the workflow only runs by push to branch, not pushed git tag
    paths-ignore:
      - '.devbots/**'
      - '.husky/**'
      - '.vscode/**'
      - .editorconfig
      - commitlint.config.js
      - license
      - docs/urls.json # By `stefanzweifel/git-auto-commit-action`, the file would be pushed alone.
  pull_request:
    paths-ignore:
      - '.devbots/**'
      - '.husky/**'
      - '.vscode/**'
      - .editorconfig
      - commitlint.config.js
      - license
      - docs/urls.json # By `stefanzweifel/git-auto-commit-action`, the file would be pushed alone.

# for `concurrency`, release should be an independent workflow. (e.g. from test, lint, etc)
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.5.1
          run_install: false # For cache

      - name: Read .nvmrc
        id: nvmrc
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"

      # pnpm should be installed before the setup-node action. REF: https://github.com/actions/setup-node/issues/530
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.nvmrc }}
          cache: pnpm

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Set Up pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        id: changesets
        with:
          commit: 'chore: release'
          title: 'chore: release'
          version: pnpm changeset version
          # Why `pnpm -r publish` instead of `changeset publish`? => For topological publish - REF: https://github.com/changesets/changesets/issues/238
          # Why `rm docs/package.json`? => Workaround of REF: https://github.com/changesets/changesets/issues/916
          publish: pnpm run changeset:publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0 # For changesets/action to commit, let's ignore husky

      - name: Add deployed docs url
        # Vercel GitHub bot automatically deploy docs pushed to production branch (`main`), regardless of GitHub Actions.
        # This step finds out the deployed docs "Preview URL".
        # Note that Vercel's "Preview URL" is static and permanent unless deleted manually.
        if: steps.changesets.outputs.published == 'true'
        run: pnpm --filter '@haetae/docs' run add-url
        env:
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_DEPLOYMENT_NAME: 'haetae'

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.changesets.outputs.published == 'true'
        with:
          commit_message: 'docs: add url'
        env:
          HUSKY: 0 # For stefanzweifel/git-auto-commit-action to commit, let's ignore husky
